### ISSUE TITLE
Forcing Syntastic into passive mode

### ISSUE THREAD

**Issue by parantapa** [vim-syntastic/syntastic#1930]
Hi

I use Syntastic in passive mode, and have a couple of filetypes as active in my vimrc.
On occasion, I find that I want to force Syntastic into passive mode even for those filetypes.
I dont want to change my vimrc every time I want to do this (and then forget to set it back).

I had submitted a PR [1] which solved this by making SyntasticToggleMode
force Syntastic into passive mode even for those files.
That PR got rejected.

Syntastic's current code hides all the state variables in script only variables.
So I cant write a command in my vimrc to get it to do what I want.
Writing something that use buffer specific passive modes
for all existing and new buffers may be possible
but is unnecessarily kludgey.

Will a PR which adds a function and command like SyntasticForcePassive
to force passive mode be accepted?

[1] https://github.com/vim-syntastic/syntastic/pull/1928

**Comment by lcd047** [comment]
> Will a PR which adds a function and command like SyntasticForcePassive to force passive mode be accepted?

You haven't thought this out too carefully, have you. Once you get to a state of forced passive mode as you suggest, regardless of how you enable it, there is no way to go back to "typed" passiveness.  Thus, no, such a change will never be considered.

> Syntastic's current code hides all the state variables in script only variables.

It's up to you to set `g:syntastic_mode_map` and `b:syntastic_mode`.  The internal variables used to track it are there only to ensure a consistent view to all components of syntastic.  They wouldn't be any use to you, even if they were to be exposed.  The "official" `g:syntastic_mode_map` and `b:syntastic_mode` take precedence over the internal state variables, all you have to do is set them at the appropriate time.

> I use Syntastic in passive mode, and have a couple of filetypes as active in my vimrc. On occasion, I find that I want to force Syntastic into passive mode even for those filetypes.

Then set `b:syntastic_mode` for the relevant files.  Or add the relevant filetypes to both `active_filetypes` and `passive_filetypes`, so that you can toggle modes for them with `:SyntasticToggleMode`:
```vim
let g:syntastic_mode_map = {
     \ "mode": "active",
     \ "active_filetypes": ["ruby", "php"],
     \ "passive_filetypes": ["ruby", "php"] }
```

**Comment by parantapa** [comment]
> You haven't thought this out too carefully, have you. Once you get to a state of forced passive mode as you suggest, regardless of how you enable it, there is no way to go back to "typed" passiveness. Thus, no, such a change will never be considered.

Forgive me, you are sounding way too condescending with your personal attacks.

What makes you think that I didn't think this through?
What makes you think such a mode is not reversible?
If a function to force Syntastic to passive mode can be written, so can be a function to restore the previous config. There is very little config to store and restore here.

> It's up to you to set g:syntastic_mode_map and b:syntastic_mode. The internal variables used to track states are there only to ensure a consistent view across all components of syntastic. They wouldn't be any use to you, even if they were to be exposed. The "official" g:syntastic_mode_map and b:syntastic_mode take precedence over the internal state variables, all you have to do is set them at the appropriate time.

I think you missed the part where I said: 
"Writing something that use buffer specific passive modes
for all existing and new buffers may be possible but is unnecessarily kludgey."

What makes you think that I am too dumb to not be able to use Syntastic's state if I had access to them?
I understand the purpose of hiding and encapsulating state, so as to not allow users make unnecessary assumptions about the internals. But to say users wouldn't be able to use it even if it were available is uncalled for.

I must say I didn't think of putting filetypes in both active and passive filetype list. I think it is very unintuitive and hackey. Never the less thanks for sharing the trick. I think it would be good to put it in the docs.

Finally, I have contributed to this project when it used to be socroolose/syntastic. I have to ill feeling towards you. This is a fantastic project. But if you want to foster a community around this project, a less condescending approach will be helpful.

Thanks

**Comment by lcd047** [comment]
> If a function to force Syntastic to passive mode can be written, so can be a function to restore the previous config.

Nope, not in any reasonable way.  An extra "forced" state would have to be tracked along with the existing states, for very little gain. _shrug_

> "Writing something that use buffer specific passive modes for all existing and new buffers may be possible but is unnecessarily kludgey."

Vim's use of `autocmd`s to configure various things per file is a kludge, yet it's 100% the Vim way. _shrug_

> What makes you think that I am too dumb to not be able to use Syntastic's state if I had access to them?

Please refrain from making assumptions about my value judgements, thank you.  A personal attack was never my intention, and neither did I say, nor did I ever imply, that missing some minute details in somebody else's game is a sign of stupidity.  Very smart people do that every day, and they aren't embarrassed by it.

> I must say I didn't think of putting filetypes in both active and passive filetype list.

Hence "you haven't thought this out too carefully"?

> But if you want to foster a community around this project, a less condescending approach will be helpful.

Since you offered me free advice, I'll offer some back.  You might consider changing your approach to handling tools from "how do I make my tool do X?" to "here's the tool, what can I do with it?".  It's my experience that you'll save a lot of time that way.  And no, I'm not trying to look down on you in any way while saying that.

I suppose it might also be a good idea to stop here.  Have a good day.
