### ISSUE TITLE
Eslint isn't run in directory without .eslintrc.json

### ISSUE THREAD

**Issue by hgiesel** [vim-syntastic/syntastic#1947]
I'm in /path/to/project/routes and my config file is /path/to/project/.eslintrc.json.
When I open /path/to/project/routes.js and type this:

```js
const fetch = require("node-fetch")
const server = "http://jsonplaceholder.typicode.com/posts/1"

let appRouter = app => {
  app.get("/foo", (req, res) => {
    fetch(server)
      .then(res => res.json())
      .then(json => console.log("parsed json", json));
  });

This is nonsense: (*&*(&^&(*&*^
}

module.exports = appRouter;
```

I expect some kind of error, how I don't  get one. when I do `:SyntasticInfo` I get

```json
Syntastic version: 3.8.0-14 (Vim 800, Darwin)
Info for filetype: javascript
Global mode: active
Filetype javascript is active
The current file will be checked automatically
Available checkers: eslint jshint
Currently enabled checker: eslint
```

**Comment by chris-fa** [comment]
so what was the issue?

**Comment by harukaeru** [comment]
I was googling and then I've reached this issue.

I have a file named `.eslintrc.js` not `.eslintrc.json`.
Can I use this `.eslintrc.js` instead of `.eslintrc.json`?

I have a project that the others manage and they use `.eslintrc.js` or `.eslintrc` as name of configuration file.

I don't know whether `vim-syntastic` has the responsibility regarding this or not, but if you know how to achieve the above, please tell me what I should do.

**Comment by lcd047** [comment]
@harukaeru Syntastic doesn't care either way.  You should consider asking on an `eslint` forum.
