### ISSUE TITLE
No matter what I do, I cannot change the ErrorSign highlighting

### ISSUE THREAD

**Issue by bitfusion-brian** [vim-syntastic/syntastic#1968]
I've broken. I'm sorry. I need help. I can't get the sign highlighting to change no matter what I do. Right now, the error sign is white foreground with no background. Here's my (shortened) vimrc:

```
" Plugins
call plug#begin('~/.vim/plugged')
Plug 'junegunn/seoul256.vim'
Plug 'moll/vim-node'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'jiangmiao/auto-pairs'
Plug 'Valloric/YouCompleteMe'
Plug 'ternjs/tern_for_vim'
call plug#end()

" Seoul color settings
let g:seoul256_background = 237
colo seoul256

---
clipped
---

" Syntastic settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1

"highlight Error term=reverse ctermfg=252 ctermbg=52 guifg=#D9D9D9 guibg=#FFD93D
" highlight SyntasticWarningSign guifg=white guibg=#FFD93D
" highlight SyntasticSyleWarningSign guifg=white guibg=#FFD93D
 "highlight SyntasticErrorSign term=reverse ctermfg=252 ctermbg=52 guifg=white guibg=#FFD93D
" highlight SyntasticSyleErrorSign guifg=white guibg=#FF3314

----
clipped
----

au Filetype javascript setl sw=3 sts=3 et
au Filetype javascript source ~/.vim-javascript

au Filetype python setl sw=2 sts=2 et

highlight Error guifg=#D9D9D9 guibg=#FFD93D
highlight SyntasticError guifg=#D9D9D9 guibg=#FFD93D
highlight SyntasticErrorSign  guifg=#D9D9D9 guibg=#FFD93D
highlight SyntasticStyleErrorSign guifg=#D9D9D9 guibg=#FFD93D
```
As you can see, I put all of my highlighting customization at the bottom. I've tried it with just setting `SyntasticErrorSign` and gotten the same result. I've tried just setting `Error` and failed. I feel like I'm missing something. 

Maybe seoul is somehow removing my ability to change the highlighting?? Any guidance will be appreciated. Even if you tear me a new one, but you educate me on how highlighting works, i'll be happy.

**Comment by lcd047** [comment]
As far as I can tell the problem has nothing to do with syntastic.  [This](https://github.com/vim-syntastic/syntastic/blob/6fb14d624b6081459360fdbba743f82cf84c8f92/plugin/syntastic/signs.vim#L54-L81) is all syntastic does to highlight signs, everything else is up to Vim.

You could try to move `highlight` definitions before `plug#begin()`, to make sure `SyntasticErrorSign` and so on are not linked to the default groups.  As far as I know it shouldn't matter, since according to `:h :hi-link`:

> - As soon as you use a ":highlight" command for a linked group, the link is removed.

If that doesn't help however, you should probably raise the issue to `seoul256` developers ad / or to `vim_dev`.  Not sure what else I could tell you.  I never had any problems with colour themes, hence I never paid much attention to them (but I'm not using a fancy colour theme, either).

**Comment by bitfusion-brian** [comment]
closing. I figured it out. Turns out my vim uses the `ctermfg/ctermbg` arguments and not `guifg/guibg`. So affecting the cterm stuff makes it work right. Thanks for the help @lcd047! You pushed me in the right direction.

**Comment by lcd047** [comment]
`guifg` / `guibg` are used for gVim, while `ctermfg` / `ctermbg` are used for terminal Vim.
