### ISSUE TITLE
invalid syntax on python

### ISSUE THREAD

**Issue by hadpasot** [vim-syntastic/syntastic#1976]
```
b = 1
print(b, end=' ')
```

it says end=' ' is invalid. why?

I am using vim8 and python3.6

**Comment by light8lee** [comment]
same with you, when I use print("lalala", file=sys.stderr). Have you fixed it yet?

**Comment by lcd047** [comment]
You get these errors because you're checking your code with Python 2.

As I stated many, many times in the past, syntastic doesn't know, nor cares about the contents of your files.  What is does is run external linters against your files, parses their output, and shows the results in a window.  That's all it does.

Now, by default the `python` checker runs a linter named (surprise!) `python`, which is probably a Python 2 binary on your machine.  To solve that you could tell the `python` checker to use Python 3 instead, by setting `syntastic_python_python_exec`:
```vim
let g:syntastic_python_python_exec = 'python3'
```
That would work for this checker, but it wouldn't do anything about other checkers you might want to run, since those checkers care about executables, not about Python versions.  For this reason, the recommended way to solve this is to create a virtual environment with `virtualenv` or `pyenv`, install there the linters you want, and run Vim from the virtual environment.  That way Vim (and thus syntastic) will get to "see" the executables corresponding to the right version of Python.  This is described in the [FAQ][FAQ].

[FAQ]: https://github.com/vim-syntastic/syntastic#faqpython

**Comment by hadpasot** [comment]
thanks.
