### ISSUE TITLE
Syntastic Flake8 - honour settings in the various ini files?

### ISSUE THREAD

**Issue by chrischambers** [vim-syntastic/syntastic#1992]
Flake8 supports project-specific configuration ordinarily by reading either tox.ini, .flake8 or setup.cfg. It seems that when I run Syntastic with ```let g:syntastic_python_checkers = ['python', 'pep8', 'flake8', 'pyflakes']```, it doesn't care about the settings in those files. Am I missing something, or is this currently not supported?

**Comment by lcd047** [comment]
Syntastic simply runs the checkers with the options you specify, it doesn't do anything special beyond that.  In order to _see_ the command lines constructed by syntastic you need to enable debugging (see `:h syntastic-debug`).  In order to _change_ the command line constructed by syntastic for `flake8` you need to set one of the `g:syntastic_python_flake8_*` options (cf. `:h syntastic-config-makeprg`).  What happens beyond that is between Vim and `flake8`.
