### ISSUE TITLE
Terminal Response displayed on screen

### ISSUE THREAD

**Issue by ryan-sandy** [vim-syntastic/syntastic#1997]
On startup, the characters, `[[>1;4205;0c` are left in the the buffer. I think this is the terminal response. Why am I seeing this?

I'm running the following version of vim:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 03 2017 08:30:30)
Included patches: 1-313, 315-540
```

**Comment by lcd047** [comment]
> Why am I seeing this?

Probably because your Vim, your terminal,  and the `termcap` / `terminfo` entry for your current `$TERM` disagree about the capabilities of your terminal.  Beyond that, who knows.  Either way however, it has nothing to do with syntastic.  Syntastic has exactly zero control over these low-level operations.  The problem you're seeing may actually be _triggered_ by syntastic, but it certainly can't be _solved_ from within syntastic.  Please see #822 for a more detailed discussion. _shrug_

**Comment by ryan-sandy** [comment]
Okay, thanks. Syntastic triggers it. Thank you for the help!

**Comment by lcd047** [comment]
> Syntastic triggers it.

Nope, that's just speculation, not a proven fact.  It's _possible_, but unlikely.  Other plugins are in far better positions for being the trigger.

**Comment by ryan-sandy** [comment]
...err when I disable the plugin the characters disappear.

**Comment by lcd047** [comment]
Still no.  The correct test is to disable all other plugins first, otherwise it could be the interaction with somebody else's `autocmd`s.  Welcome to the wonderful world of debugging Vim code.

**Comment by Viterzgir** [comment]
After update syntastic plugin have same issue. After disable check file on open charater is disappear.
let g:syntastic_check_on_open = 0

**Comment by lcd047** [comment]
@Viterzgir ... But only when you open the file on the command line, with `vim file`, right?  If you leave `g:syntastic_check_on_open = 1`, run vim, then open the file with `:e file`, everything is fine?

**Comment by Viterzgir** [comment]
@lcd047  Yep only with vim file open.

**Comment by lcd047** [comment]
@Viterzgir Then it's probably a bug in Vim, but it's still hard to tell what exactly the bug is.  It's pretty much obvious that some functions are unsafe to be called from starup `autocmd`s, and syntastic is probably making some unsafe calls like that.  Sadly nobody has yet identified these functions, let alone listed them in the docs.  Actually, preciously few people seem to understand in detail what's _really_ going on at Vim startup.  I'm certainly not one of them, I'm playing by the documented rules. _shrug_

**Comment by ryan-sandy** [comment]
@lcd047 This is 100% a problem with VIM. I've updated my vim and the problem has gone away. Thank you for your help!
