### ISSUE TITLE
Question about `syntastic_python_pylint_post_args`

### ISSUE THREAD

**Issue by merryChris** [vim-syntastic/syntastic#2007]
I just want to set g:syntastic_python_pylint_post_args specifically after reading [pylint output doc](https://pylint.readthedocs.io/en/latest/user_guide/output.html). But after setting it like '--msg-template="[{msg_id}]:{line:3d},{column:2d}: {symbol}: {msg}"', I find it doesn't work with `syntastic`, however it works fine with shell.

Here is what the `syntastic` doc says, 

> Please note that the new format must start with "{path}:{line}:{column}:{C}: ", otherwise syntastic will not recognise any messages.

Could anyone explain the reason? Thanks so much.

**Comment by lcd047** [comment]
The reason `--msg-template="[{msg_id}]:{line:3d},{column:2d}: {symbol}: {msg}"` doesn't work? Because the new format doesn't start with `{path}:{line}:{column}:{C}: `.

The reason the new format has to start with `{path}:{line}:{column}:{C}: `?  Because syntastic relies on parsing error messages with `errorformat`, and syntastic's `errorformat` has to agree with the format of messages produced by `pylint`.

**Comment by merryChris** [comment]
It seems that `{path}:{line}:{column}:{C}:` is shown like `xxx.py|123 col 4 warning|` in my vim loc list. Can this part be configured by `syntastic`?

**Comment by lcd047** [comment]
> Can this part be configured by `syntastic`?

No.  The error window is managed by Vim (see `:h quickfix.txt`), and its format is not configurable.

**Comment by merryChris** [comment]
OK, thanks. ;)
