### ISSUE TITLE
Why  can't check out the lost  `} ` at the end of the line with csslint?

### ISSUE THREAD

**Issue by yufeiluo** [vim-syntastic/syntastic#2032]
syntastic installed in vim,to install csslint with npm.

    sudo npm install csslint -g

To check a css file with only one line in it.

    body,ul,li,input,p,dl,dt,dd,h1{margin:0;padding:0;box-sizing:border-box; 

1.to check with csslint command.

csslint  test.css

csslint: There are 3 problems in  test.css

test.css
1: warning at line 1, col 51
The box-sizing property isn't supported in IE6 and IE7.
body,ul,li,input,p,dl,dt,dd,h1{margin:0;padding:0;box-sizing:border-box; 

test.css
2: error at line 2, col 1
Expected RBRACE at line 2, col 1.

test.css
3: error at line 2, col 1
Expected RBRACE at line 2, col 1.

2.to check with syntastic and csslint
 
Here is the checked info.

[![enter image description here][1]][1]

Why the important error--no } to end the css statement  can't be checked with csslint?    

  [1]: https://i.stack.imgur.com/rHEl4.png

**Comment by lcd047** [comment]
> Why the important error--no } to end the css statement can't be checked with csslint?

It can, but you chose not to look at the error.  When you open the error window:
![2017-06-18-104207_679x176](https://user-images.githubusercontent.com/1281736/27259044-ec3f929c-5412-11e7-9e9d-c81aff847099.png)
What's going on here is that `csslint` shows errors for line 2, which doesn't exist in the file.  Syntastic can move those errors to the last line in file, but in the particular case of `csslint` it doesn't.  This is a bug; fixed in commit f459416d.  However, that won't make the error take priority over the warning alrteady on line 1, because `postprocess` functions are applied after sorting messages.  So you still won't be able to see the error when you only use cursor notifications.  Sadly there is no way to fix that without breaking other checkers.
