### ISSUE TITLE
reloading without :w?

### ISSUE THREAD

**Issue by plexigras** [vim-syntastic/syntastic#2035]
i want to lint via keybinding or even completly automaticlly on bufer change but i cant figure out how without writing to disk first.

**Comment by lcd047** [comment]
Syntastic can't do that, sorry.  There are plugins that can do it for a few particularly well-behaved combinations of languages and linters, but syntastic can't.  With syntastic's approach to linting, syntastic doesn't know nor cares about files on disk, and the linters don't know nor care about Vim buffers.  That's part of the price syntastic has to pay for being able to to talk to 240+ different linters for 100+ different languages.

**Comment by plexigras** [comment]
so is there a way around this using a temp file or something?

**Comment by lcd047** [comment]
The workarounds are to either write the file to disk (i.e. us the functionality provided), or switch to something else that provides the functionality you want.

For what it's worth, a temporary file won't work since many linters run checks against the full project rather than against a single file.

**Comment by plexigras** [comment]
ok thanks for the info.
