### ISSUE TITLE
Enable eslint for "javascript.jsx"

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [vim-syntastic/syntastic#2039]
Hello,

I have "javascript/eslint" available for "javascript.jsx" files but I can't enable it.

I read the FAQ and it should be 

`let g:syntastic_javascript.jsx_checkers = ['eslint']`. But obviously having a dot in a variable name is forbidden.

How can I do it ?

**Comment by lcd047** [comment]
Please refer to `:h syntastic-composite`.  If that doesn't address your problem please restart Vim, open your test file, run `:SyntasticInfo`, and post the output.

**Comment by GuillaumeLeclerc** [comment]
For people searching for this issue:

`let g:syntastic_javascript_checkers = ['eslint']` 

worked.

**Comment by danheberden** [comment]
Adding for future folks:

I have vim-javascript and vim-jsx installed (resulting in a `javascript.jsx` ft).

Ultimate, my issues were in trying to do something like `let g:syntastic_javascript_eslint_exe = 'npm run lint --'` The solution was to install `eslint-cli` instead of trying to get syntastic to run custom code (which apparently doesn't work with mapped ft's). That way my config was what you'd expect:

```
let g:syntastic_javascript_checkers = ['eslint']
```
