### ISSUE TITLE
Error Explanation Mappings

### ISSUE THREAD

**Issue by dimndskier** [vim-syntastic/syntastic#2064]
I am very new to syntastic as a plugin to vim (thanks for the module).

But, I don't have a full understanding of what I am reading on the screen so I don't know what to do about it.  I know I am the problem, but in this case I don't know how to read the error to know what action to take.

At the bottom of my vim session as I am modifying a Puppet-related ERB template file I see the following:

`>>172 # end of the forwarding rule #
  173 <% end -%>
[Syntax: line:86 (2)]
  1 rsyslog.conf.new.el.erb|86 warning| possibly useless use of a variable in void context
  2 rsyslog.conf.new.el.erb|172 warning| possibly useless use of a variable in void context
`

Am I concerned about the "Syntax: line:86 (2)" or the "|86 warning|" and the "|172 warning|"; finally what do any of them mean, besides the statement "_possibly useless use of a variable in void context_" ?

Thanks,

**Comment by lcd047** [comment]
If you're new to Vim you shouldn't be using syntastic.  Syntastic is a development tool, in order to take advantage of it you need a working knowledge of Vim scripting, and a good understanding of all other tools involved.  Syntastic is not supposed to work out of the box, nor is it offering much hand holding.  It certainly doesn't offer explanations for messages produced by linters.

To answer your question though: don't use `erb` checkers to check Puppet manifests.  Use modelines (see `:h modeline`) to make sure the files you're checking have the `puppet` filetype, and use `puppet` checkers to check them.  When you do that you'll probably no longer get the messages above.

**Comment by dimndskier** [comment]
Thanks @lcd047.  I am not really new to vim or vi; I just have never programmed/configured plugins for vim/vi.

I will take your feedback though and turnoff syntastic.  I will also check into ':h modeline' and see what I can learn.

Thanks again.
