### ISSUE TITLE
Syntastic only applies php checkers on custom files after writing `<?php` tag

### ISSUE THREAD

**Issue by t-ionut** [vim-syntastic/syntastic#2085]
I've installed Syntastic and have the following settings in my `.vimrc`:
```
let g:syntastic_inc_checkers = ['php', 'phpcs', 'phpmd']
let g:syntastic_module_checkers = ['php', 'phpcs', 'phpmd']
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_aggregate_errors = 1
```
I wanted to enforce PHP checkers on `.inc` and `.module` files for my work on Drupal projects. However, if I open a new file called `foo.inc` and do `:SyntasticInfo` I get this, same for `foo.module`:

```
Syntastic version: 3.8.0-87 (Vim 704, Linux)
Info for filetype: pov
Global mode: active
Filetype pov is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
The current file will not be checked (file not readable / not local)
```
I can also type in anything as long as I omit the `<?php` starting tag, I will not get any errors and it will not use `php`-like checkers on my file. Only after I put a `<?php` starting tag in my file, `:wq` and open it again, it will start showing me errors and show the `php` checkers in `Available checkers` when doing `:SyntasticInfo`.

I'm no VimScript expert and this is not a big bother, but still, I'd like to get my custom files checked under any circumstances.

**Comment by lcd047** [comment]
Sadly, using syntastic requires familiarity with a number of Vim concepts.  Syntastic checks files based on `filetype` (see `:h filetype`) rather than based on file extensions.  In particular there are no such things as `g:syntastic_inc_checkers` and `g:syntastic_module_checkers`, there is only `g:syntastic_php_checkers`.

Now, `filetype` is normally detected by Vim, but the detection is largely heuristic.  In your case your files are detected as `pov`:

> `Info for filetype: pov`

You can override the detected `filetype` with a `modeline` (cf. `:h modeline`).  So just set `g:syntastic_php_checkers`, and add something like this near the top (or bottom) of your files:
```php
# vim: filetype=php
```
