### ISSUE TITLE
Syntastic freezes for minutes when saving D files

### ISSUE THREAD

**Issue by sasq64** [vim-syntastic/syntastic#2086]
As topic says, saving from Vim makes it freeze for a long time. It used to work, and I hadn't upgraded the plugin when it started happening so something else must have triggered it.
ver 3.8.0-65
Vim 8.0

**Comment by lcd047** [comment]
`dmd` is one of those checkers that tries to be [fancy][dmd] and runs `dub` to detect include directories.  You probably made changes to your installed packages that make `dub` run slower.  Please open your test file, set `g:syntastic_debug` to 33, save your file (wait for the checker to finish running), run `:mes`, and post the output.  Then read `:h syntastic-profiling`, run a profiling trace, upload the logs somewhere, and post the link.

In the mean time you can turn `d` passive (cf. `:h 'syntastic_mode_map'`), so that you won't run the checker every time you save files.

[dmd]: https://github.com/vim-syntastic/syntastic/blob/cd871da6b4515e393ec0ba885423594447980e09/syntax_checkers/d/dmd.vim#L62

**Comment by lcd047** [comment]
Ping.

**Comment by sasq64** [comment]
Sorry, I had turned off syntastic and when I reenabled it I didn't get the freeze anymore. Feel free to close this until I see it again and can provide some debug info.
