### ISSUE TITLE
Add OpenCL checker

### ISSUE THREAD

**Issue by petRUShka** [vim-syntastic/syntastic#2095]
I propose to add OpenCL checker. 

There is [clcc](http://clcc.sourceforge.net/) compiler for such cases. And VIM code for this can be stolen from [here](https://github.com/petRUShka/vim-opencl/blob/master/syntax_checkers/opencl/clcc.vim):

```viml
function! SyntaxCheckers_opencl_clcc_GetLocList() dict
    let makeprg = self.makeprgBuild({ 'exe': 'clcc' })

    " Intel beignet format
    let errorformat  =  '%E%f:%l:%c: error: %m,%-Z,'.
                       \'%W%f:%l:%c: warning: %m,%-Z,'
    " pocl format
    let errorformat .=  '%Eerror: %.%#:%l:%c: %m,%-Z,'
    " NVIDIA driver format
    let errorformat .=  '%E:%l:%c: error: %m,%-Z%p^\[ ~\]%#,'.
                       \'%W:%l:%c: warning: %m,%-Z%p^\[ ~\]%#,'.
                       \'%I:%l:%c: note: %m,%-Z%p^\[ ~\]%#,'
    " AMD driver format
    let errorformat .=  '%E"%f"\, line %l: catastrophic error: %m,%+C%.%#,%-Z%p^,'.
                       \'%E"%f"\, line %l: error: %m,%+C%.%#,%-Z%p^,'.
                       \'%W"%f"\, line %l: warning: %m,%-C%.%#,'
    " Other lines should be hidden
    let errorformat .= '%-G%.%#'

	let loclist = SyntasticMake({ 'makeprg': makeprg, 'errorformat': errorformat })

    " the file name isnt in the output so stick in the buf num manually
	for i in loclist
      let i['bufnr'] = bufnr("")
	endfor

    return loclist
endfunction
```

**Comment by lcd047** [comment]
Your code in [`vim-opencl`][vim-opencl] works fine as an [external checker][wiki], it just needs some minor cleanup.  I'll send you a PR right away.

This is preferable to inclusion in syntastic for two reasons:

1. you actually use OpenCL and care about that code, and
2. the licence you chose for your checker is not compatible to syntastic's license.

On an unrelated note: your `errorformat` looks fishy.  I can't really check it since I'm not using OpenCL myself, but things like `%-Z` in multiple places rarely make sense.  Vim manual is less than helpful here, I'd suggest you should look at `src/quickfix.c` in Vim's sources to get a complete understanding of how `errorformat` matching _actually_ works.

[vim-opencl]: https://github.com/petRUShka/vim-opencl
[wiki]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide#external

**Comment by petRUShka** [comment]
Thanks for your PR!

Actually CUDA (for which syntastic has checker) and OpenCL have quite same status for GPGPU computing :) I mean that it would be good to have both of them as official checkers.

I can change licence for whatever that isn't a problem I think. Could you provide as minimal as poosible docs example?

**Comment by petRUShka** [comment]
> On an unrelated note: your errorformat looks fishy. I can't really specific problems since I'm not using OpenCL myself, but things like %-Z in multiple places rarely make sense. Vim manual is less than helpful here, I'd suggest you should look at src/quickfix.c in Vim's sources to get a complete understanding of how errorformat matching actually works.

Thanks for that note! I'll look at it!

**Comment by lcd047** [comment]
> I mean that it would be good to have both of them as official checkers.

Actually, it would be better if both would be external checkers.  External checkers are maintained by people who use the corresponding tools and care for them.  Personally I don't know anything about either, and much less care, to be honest.  Thus sorry but no.
