### ISSUE TITLE
Provide example to set `PATH` for Syntastic checkers

### ISSUE THREAD

**Issue by nhooey** [vim-syntastic/syntastic#2099]
The FAQ mentions that your preferred checker might not be running because it's not in Vim's path, but it doesn't give an example command to set that path.

It would be convenient if an example was there.

**Comment by lcd047** [comment]
Changing Vim's `PATH` is dependent on user's environment, and it can range from trivial to pretty esoteric (f.i. when you're running Vim from a menu in a desktop environment). :smile: There is no way to describe all that in the FAQ without muddying waters even further.

On the other hand, syntastic is a development tool, and relies on people having a good understanding of what they're doing.  In particular, the brute force way to deal with irregular paths is to set `syntastic_<filetype>_<checker>_exec`, which is described in the manual.

**Comment by jablko** [comment]
The following worked for me:
```
:let $PATH = system('yarn bin')[:-2] . ':' . $PATH
```

- Syntastic will use checkers (e.g. `eslint`) installed in `node_modules` before ones installed on the system. If you want it the other way around (system before `node_modules`), use `:let $PATH .= ':' . system('yarn bin')[:-2]`
- The `$PATH` [environment variable](https://vimhelp.org/eval.txt.html#%3Alet-environment) is global. I'm not sure if there's a [local](https://vimhelp.org/eval.txt.html#buffer-variable) solution, or a way to set it just for Syntastic calls?
- `yarn bin` will find the project `bin` folder. It works in project subdirectories. `npm bin` should work too.
- I don't know my Vimscript, I think it doesn't do string interpolation? e.g. `':$PATH'`
- I tried [`backtick-expansion`](https://vimhelp.org/editing.txt.html#backtick-expansion), e.g. `` `yarn bin` ``. It didn't work in this context :disappointed:
- `[:-2]` is necessary because `yarn bin` (like most commands) outputs a trailing newline. `[:-1]` wasn't enough, presumably because the output ends in `\r\n`?

Is there a better way?

**Comment by lcd047** [comment]
> Is there a better way?

Yes, depending on what problem you're _actually_ trying to solve.
