### ISSUE TITLE
REMOVE PEP257 from various locations

### ISSUE THREAD

**Issue by alphaCTzo7G** [vim-syntastic/syntastic#2106]
Hi

I noticed that PEP257 is still mentioned at various locations in syntastic, which tends to make it confusing for the new user of syntastic:
1.	https://github.com/vim-syntastic/syntastic/wiki/%28v3.7.0%29---Python%3A---pep257
2.	https://github.com/vim-syntastic/syntastic/wiki/%28v3.7.0%29---Syntax-Checkers
3.	https://github.com/vim-syntastic/syntastic/tree/master/syntax_checkers/python

I spent sometime, confused why there is pep257 mentioned, in the above locations, but not in the syntax checkers (https://github.com/vim-syntastic/syntastic/blob/master/doc/syntastic-checkers.txt) in the manual.

Later, I noticed that there is note saying the PEP257 has been renamed to pydocstyle (https://github.com/PyCQA/pydocstyle).

Can we remove pep257 folders and references from syntastic. There is no need to use pep257, as far as I can tell, and it will improve the out-of-the-box experience for new users.

**Comment by lcd047** [comment]
> I spent sometime, confused why there is pep257 mentioned, in the above locations, but not in the syntax checkers

Did you read the bold text in the [Syntax Checkers](https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checkers) page in the wiki?

> Can we remove pep257 folders and references from syntastic.

`pep257` is mentioned in the wiki as a checker for syntastic 3.7.0 and earlier.  This is correct, the current version of syntastic is 3.8.0, and versions 3.7.0 and earlier didn't support `pydocstyle`, but did support `pep257`.  Removing the reference from the docs for old versions doesn't accomplish anything useful.

`pep257` also exists as a checker in the latest version of syntastic.  This is for backwards compatibility only, which is why it isn't documented.  Removing it doesn't accomplish anything useful, either.

In the interest of saving time I suggest you either read the provided docs in their logical order, or, if you must read the sources without bothering with the docs, take your time to understand what is actually going on.
