### ISSUE TITLE
Rubocop checks ignores the Excluded part of AllCops part of configuration

### ISSUE THREAD

**Issue by ozzyaaron** [vim-syntastic/syntastic#2137]
According to this issue when using Rubocop to check individual files you should include `--force-exclusion` otherwise Rubocop will ignore Exclusions in the AllCops section.

When using the following snippet

```
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*.rb'
```

Syntastic will still show issues found by Rubocop in `schema.rb` and migrations. 

My setup:

```
:ver
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  8 2018 07:50:03)
macOS version
Included patches: 1-1420
Compiled by Homebrew   
```

```
Syntastic version: 3.8.0-101 (Vim 800, Darwin, GUI)
Info for filetype: eruby.yaml
Global mode: active
Filetype eruby.yaml is active
The current file will be checked automatically
Available checker: eruby/ruby
Currently enabled checker: eruby/ruby  
```

**Comment by ozzyaaron** [comment]
Hey there, I tried to follow the Contributing guidelines. I'm using the above patch locally and it appears to work.

**Comment by lcd047** [comment]
Please see #1641.

**Comment by ozzyaaron** [comment]
Thanks @lcd047 I tried searching a few times but didn't get anything. Would you accept a PR that adds to the FAQ part of documentation? 

I see your point in the linked PR but I also cannot see a reason why people would not want the checker in their editor to behave the way that `force-exclusion` behaves.

Happy to PR a doc change if you would want that.

**Comment by lcd047** [comment]
> Would you accept a PR that adds to the FAQ part of documentation?

It isn't really a FAQ (but see also below).

> I see your point in the linked PR but I also cannot see a reason why people would not want the checker in their editor to behave the way that `force-exclusion` behaves.

There are a number of issue here.

First, the way I see it this is an usability problem with `rubocop`, not with syntastic.  As a matter of principle syntastic doesn't try to fix this kind of problems, because doing that goes against syntastic's goal of being linter-agnostic.  Also, if the linter's author is happy with (supposedly) broken default, then syntastic can be equally happy.  Have you considered asking `rubocop`'s author to make `--force-exclusion` default when linting a single file, rather than passing the problem downstream to the editors and whatever else?

Second, this is the wrong fix.  It isn't _broken_, but it still isn't right.  Syntastic has general mechanisms for preventing checks for particular files.  Inventing yet another mechanism just for `rubocop` is bad design.

Then, syntastic doesn't necessarily check a single file at a time.  You can tell syntastic to pass something else than the current file to `rubocop` by setting `syntastic_ruby_rubocop_fname` (and several checkers put that to very good use).  Then `--force-exclusion` becomes pointless (or wrong).

For the same reason, adding `--force-exclusion` to `args_after` is wrong, because it can't be overridden by the user.

Last but not least, did you check whether `--force-exclusion` is supported by _all_ versions of `rubocop` supported by syntastic?  If it isn't, then the fix has to be applied only to the right versions.

I could go on, but turning this into a mini-essay doesn't look very appealing at this time.  Sorry about that.

**Comment by ozzyaaron** [comment]
@lcd047 thanks for the info, that all makes sense. 

I think after reading your mini-essay 😄I think I would probably reword my claim as 

> ... I also cannot see a reason why rubocop's default behavior isn't to use force-exlusion

Which as you rightly point out is not a problem for every consumer to fix themselves. 

Thanks!
