### ISSUE TITLE
Syntastic fails to parse the tilda character (user home dir) in custom include paths

### ISSUE THREAD

**Issue by mattconway1984** [vim-syntastic/syntastic#2140]
With syntastic configured so it knows where to search for "custom" includes through creating a configuration file that looks something like this:

**.config/vim/foo_includes.syntastic**

```
-I/var/foo_sdk/include
-I/var/bar_sdk/include
-I~/.local/include
```
And in the **.vimrc** file:

```
let g:syntastic_cpp_config_file='~/.config/vim/foo_includes.syntastic'
```

You will run into this type of error: "fatal error: custom.h: No such file or directory".

Re-running this with some extra debug to find out what's going on:

`SyntasticMake: called with options: {'postprocess': [], errorformat': '%-G%f:%s:,%f:%l:%c: %trror: %m,%f:%l:%c: %tarning: %m,%f:%l:%c: %m,%f:%l: %trror: %m,%f:%l: %tarning: %m,%f:%l: %m', 'makeprg': '''g++'' -x c++ -fsyntax-only  -I. -I.. -Iinclude -Iincludes -I../include -I../includes ''-I/home/[username]/.vim/~/.local/include'' -I/var/foo/include -I/var/bar/include some_file.cc'}`

Clearly shows that the issue is in the expansion of the '~' character which should be "path to users home directory" - it seems syntastic does not handle this, because the line in the configuration file:

**-I~/.local/include**

Should equate to:

**-I/home/[username]/.local/include**

But looking at the debug, it is actually becoming:

**-I/home/[username]/.vim/~/.local/include**

**Comment by lcd047** [comment]
"Doctor, it hurts when I do X." :smile:

Config files are deliberately dumb.  They have a single feature, expansion of relative paths with `-I`.  They have no concept of quoting.  Expanding `~` would require extending the format for config files to understand quoting, because otherwise you wouldn't be able to pass unexpanded `~`.

This is Vim.  How about `:s!^-I\zs\~!/home/user!`.
