### ISSUE TITLE
Checker Do Actual Computation (lang: SML) (bug?)

### ISSUE THREAD

**Issue by SAMFYB** [vim-syntastic/syntastic#2152]
Hi,

I'm using Syntastic for Standard ML. The syntax checker (automatically upon opening the source file) seems to be evaluating my program.

I realize this because I have an expression evaluating Ackermann function on (4, 1). Opening the file takes really long time. When I __disable__ Syntastic, opening the file becomes instant fast.

Is there a way to get around this? Or is this something to do with the checker itself?

Thank you!

**Comment by lcd047** [comment]
* In order to see what syntastic does you can enable debugging (cf. `:h syntastic-debug`).
*  In order to turn off automatic checking of your files you can set `sml` as a passive filetype (cf. `:h 'syntastic_mode_map'`).
* In order to check files in background you can use an asynchronous checker instead of syntastic, such as [ale][ale].

[ale]: https://github.com/w0rp/ale
