### ISSUE TITLE
use compilation database for finding headers instead of manually enumerating them

### ISSUE THREAD

**Issue by PreslavMihaylov** [vim-syntastic/syntastic#2154]
Currently, when I enable syntastic on a large project, I get too many "header not included error".
In order to fix this, I have to make a syntastic-specific configuration file where I enumerate all the header locations in the project.
```
let g:syntastic_c_include_dirs = [ '../include', 'include' ]
```

That can suffice for specific projects, where all headers are located in the `include` directory, but if the headers are spread out all across the system, then it is pretty tedious to locate all header locations on the system. And if new header locations are added, this configuration file should be manually modified again.

And even if you succeed at doing that and even automating it, then the problem persists, when **there are different builds for the project in the same codebase**.

That latter problem will mean that you will get faulty compilation errors in headers, not even included in your current build.

In order to fix this problem, I suggest using an approach similar to `YouCompleteMe`:
[YouCompleteMe Compilation Database](https://github.com/Valloric/YouCompleteMe#option-1-use-a-compilation-database)

If such a thing is implemented, then all you need to do is run:
`bear make` and you are set to go.

What `bear` does is to extract a `json` file from the make command, which can later be used by syntastic to detect the **relevant symbols for the current build**.

**Comment by lcd047** [comment]
Unlike YCM, syntastic doesn't care about the contents of your files.  What syntastic does is run linters against your files, parse the results, and show them to you in a window.  Consequently support for compilation databases is already there for the linters that support such things, and can't be implemented for linters that don't.  Enabling the use of compilation databases for the few linters that support them is described in the manual (f.i. `:h syntastic-cpp-clang_tidy`).

That said, Vim + syntastic is not a good choice for checking projects that use compilation databases, mainly because syntastic tries to provide a generic framework rather than integrating with particular build systems.  Other plugins such as YCM might fare better.
