### ISSUE TITLE
Signs sometimes not showing

### ISSUE THREAD

**Issue by tuzz** [vim-syntastic/syntastic#2156]
I'm using Syntastic with both Ruby and Rust. When I save a Ruby file with a syntax error the signs appear next to the line. When I do the same with a Rust file they don't. I'm using the latest Syntastic and [rust.vim](https://github.com/rust-lang/rust.vim). I'm running the latest Vim from Homebrew.

These are my configuration settings:

```vim
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_rust_checkers = ['cargo']
```

If I open the location list and select an item then the signs do appear. I've looked through all the syntastic configuration (and some of the source code), but I couldn't figure out how to make the signs appear automatically for Rust files. Is this a bug?

Thanks

**Comment by lcd047** [comment]
Showing and hiding signs is controlled by Vim, not by syntastic.  Also syntastic doesn't have native support for Rust.  Now, from a quick check I don't see anything in `rust.vim` that would prevent signs from working, but I'm not familiar with the code.  You might try asking there, but if they don't do anything special about signs then the problem is likely to be with Vim.

**Comment by tuzz** [comment]
Thanks. It's working fine with Ruby, so I don't think it's something misconfigured in my Vim. I guess I'll ask in `rust.vim`.

**Comment by lcd047** [comment]
It working with Ruby means there isn't anything wrong with syntastic.  It doesn't say anything about bugs in Vim.

**Comment by tuzz** [comment]
I found [this issue](https://github.com/rust-lang/rust.vim/issues/196) which seems to be the same thing. Closing this. Thanks for the help.
