### ISSUE TITLE
terminal and vim become unresponsive when attempting to edit a python file.

### ISSUE THREAD

**Issue by geoolson** [vim-syntastic/syntastic#2181]
I can start a new python file with vim but I start running into issues when I save the file. Sometimes syntastic will check and catch errors. Then I will make correction and save again then the cursor will stop flashing on my terminal and then I have to kill vim to get my terminal to return to normal. If I attempt to reopen the file the same issue returns. This issue only exists with python files. 

If I add this line into my .vimrc:

`let g:syntastic_ignore_files = ['\.py$']`

the problem goes away but then syntastic is no longer working on python files.

**Comment by lcd047** [comment]
Your expectations are unrealistic, syntastic runs linters synchronously.  You can configure it to run fewer and / or faster linters, and you can also configure it to run linters only when you tell it explicitly rather than when the current buffer is written, but the checks are still done synchronously.  You're probably better looking for a plugin that runs linters asynchronously, such as [ALE][ALE].

[ALE]: https://github.com/w0rp/ale

**Comment by geoolson** [comment]
Excuse me, what's unrealistic? I was under the impression syntastic supports python. This issue only exists with python. I'm not running into issues with other file formats.

**Comment by lcd047** [comment]
Syntastic doesn't "support python".  What syntastic does is run third party linters for various languages, parse their output, and show you the results in a window.  Some of said linters are fast, others are slow; this has nothing to do with syntastic, and there isn't anything syntastic can do to change that.  Your issue "only exists with python" because the Python linters you're running happen to be slower than the linters for other languages.

That said, you don't have to take my word for it.  Feel free to enable profiling (cf. `:h syntastic-profiling`) and provide proof there's something special with Python checkers that makes them slower than other checkers, and the bottleneck is within syntastic's code. _shrug_

**Comment by geoolson** [comment]
>Your issue "only exists with python" because the Python linters you're running happen to be slower than the linters for other languages.

How do you know this has to do with the linter/s running too slow?
