### ISSUE TITLE
Writing any Scala file is slow (~2-3 seconds)

### ISSUE THREAD

**Issue by jvican** [vim-syntastic/syntastic#2201]
Syntastic invokes either fsc or Scalac on every write to Scala files. However, these compilers run on the JVM and are therefore really slow to start up. It would be great to replace these two options by Scalameta's native parser (/cc @xeno-by), whenever it can be installed in people's machines. This would avoid slowing down any development of Scala code in vim.
  
In the meanwhile, Scala developers have the option of using [`scala-vim`](https://github.com/derekwyatt/vim-scala) (which implements its own parsing logic and has been heavily battle-tested) and disabling checking Scala files with `let g:syntastic_ignore_files = ['\m\.sbt$','\m\.scala$']`.

**Comment by lcd047** [comment]
> Syntastic invokes either fsc or Scalac on every write to Scala files. However, these compilers run on the JVM and are therefore really slow to start up.

You can save a lot of time by investing a few minutes in reading the manual.  If you set `scala` as a passive filetype (cf. `:h 'syntastic_mode_map'`) syntastic will attempt to check `scala` files only when you run `:SyntasticCheck` explicitly (cf. `:h :SyntasticCheck`).  If you set `g:syntastic_scala_checkers` to an empty list `[]` syntastic will never try to check `scala` files (cf. `:h syntastic-filetype-checkers`).

> It would be great to replace these two options by Scalameta's native parser

There is a [guide][guide] fore writing syntastic checkers.  Working patches are appreciated.

> In the meanwhile, Scala developers have the option of using [`scala-vim`](https://github.com/derekwyatt/vim-scala) (which implements its own parsing logic and has been heavily battle-tested)

Are you suggesting that syntastic checkers `fsc` and `scalac` should be removed in favor of [`scala-vim`][scala-vim]?  This would be in line with the way syntastic is going these days.  So sure, I'll do it, if you can get a few other Scala people to vouch for it.

> disabling checking Scala files with `let g:syntastic_ignore_files = ['\m\.sbt$','\m\.scala$']`.

As syntastic cares about `filetype`s rather than file extensions, that's the wrong way to do it.  The better ways are the ones suggested above.

[guide]: https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide
[scala-vim]: https://github.com/derekwyatt/vim-scala

**Comment by jvican** [comment]
> You can save a lot of time by investing a few minutes in reading the manual. If you set scala as a passive filetype (cf. :h 'syntastic_mode_map') syntastic will attempt to check scala files only when you run :SyntasticCheck explicitly (cf. :h :SyntasticCheck). If you set g:syntastic_scala_checkers to an empty list [] syntastic will never try to check scala files (cf. :h syntastic-filetype-checkers).
  
I did `:help syntastic` and then grepped for scala. I didn't find anything, so had to work around it. I grant you I didn't check the manual thoroughly, I was more interested in side-stepping this problem :smile:
  
> As syntastic cares about filetypes rather than file extensions, that's the wrong way to do it. The better ways are the ones suggested above.
  
Thanks for pointing out better ways of fixing the issue.
  
> Are you suggesting that syntastic checkers fsc and scalac should be removed in favor of scala-vim? This would be in line with the way syntastic is moving these days. So sure, I'll do it, if you can get a few other Scala people to vouch for it.
  
This would be great. `fsc` and `scalac` are JVM-based compilers, so it seems overkill to me to use them to check syntax. I won't devote much time to convince people this is the right way to do it, but I think that interested parties could file a ticket in vim-scala and see what happens from there. Having some kind of centralized syntax rules would make sense, especially if we have in mind that there will be some slight modifications in Scala 3.
  
> There is a guide for writing syntastic checkers. Working patches are appreciated.
  
A Scalameta parser implementation would only be possible whenever Scalameta releases native binaries (it's in their roadmap). I don't have time to implement the patch unfortunately.
  
I mostly opened this issue to ease discoverability of this problem, as I imagine other Scala developers have run into this issue in the past.

**Comment by xeno-by** [comment]
> A Scalameta parser implementation would only be possible whenever Scalameta releases native binaries (it's in their roadmap).

We're almost there. We're publishing prereleases of the native parser for a few months now (https://oss.sonatype.org/content/repositories/releases/org/scalameta/parsers_native0.3_2.11/), so the final Scalameta 4.0 release should include a native parser.
