### ISSUE TITLE
All signs are errors (no warning sign)

### ISSUE THREAD

**Issue by vivoconunxino** [vim-syntastic/syntastic#2231]
I've configured syntastic to check php errors and phpmd syntax warnings. All I see are errors, with the error sign and highlight (even the syntax ones, marked as x). Did I miss anything? I expected the syntax ones to be warnings (⚠).

My syntastic config:
```
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 0
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
"no annoying code sniffer errors
let g:syntastic_php_checkers = ['php', 'phpmd']
let g:syntastic_error_symbol='✗'
let g:syntastic_warning_symbol='⚠'
let g:syntastic_style_error_symbol = '✗'
let g:syntastic_style_warning_symbol = '⚠'
let g:syntastic_enable_signs = 1

let g:syntastic_mode_map = {
            \ "mode": "passive",
            \ "active_filetypes": ["ruby", "php"],
            \ "passive_filetypes": ["puppet"] }


```

**Comment by lcd047** [comment]
Syntastic has syntax checkers and style checkers (the distinction is pretty much [arbitrary](https://github.com/vim-syntastic/syntastic#faqstyle)).  Each of them can in principle (depending on the corresponding linter's capabilities) recognize errors and warnings.  So you can have syntax errors and warnings, and style errors and warnings.  You can configure syntastic to show different signs for them using `error_symbol`, `warning_symbol`, `style_error_symbol`, and `style_warning_symbol`.

Now, `php` is s syntax checker, and it can produce only errors (the linter doesn't distinguish between errors and warnings).  On the other hand `phpmd` is a style checker, and it can also produce only errors (the linter doesn't distinguish between errors and warnings).  Since you configured both `g:syntastic_error_symbol` and `g:syntastic_style_error_symbol`  to be `✗`, you won't be able to see any difference between them.

**Comment by vivoconunxino** [comment]
Thanks a lot
