### ISSUE TITLE
Python 2 vs Python 3 in codec.py and compile.py

### ISSUE THREAD

**Issue by praiskup** [vim-syntastic/syntastic#2248]
Should we execute those files by python2, python3, or does it matter?  Or should this be an user decision thing?

**Comment by praiskup** [comment]
I'm asking because we package `vim-syntastic` and the shebang `#/usr/bin/python` isn't correct according to Fedora guidelines, so I am supposed to change it to either python2 or python3.

**Comment by lcd047** [comment]
> Should we execute those files by python2, python3, or does it matter?

It's supposed to work with either, syntastic tries hard not to care.  The same problem extends to the other Python checkers (`pyflakes`, `pylint`, etc.), so instead of trying to provide a version switch from inside Vim, the recommended way to deal with the Python (and Ruby) version mess is to [run Vim in a virtual environment][venv].

> Or should this be an user decision thing?

It should be an user decision.  It doesn't make much sense to check a Python 2 script with Python 3 checkers, or the other way around. :smile:

> I'm asking because we package `vim-syntastic` and the shebang `#/usr/bin/env python` isn't correct according to Fedora guidelines, so I am supposed to change it to either python2 or python3?

The shebang is not used, it matters only when running said scripts outside syntastic (presumably for purposes related to syntastic development).  Syntastic runs it like this:
```sh
python /path/to/compile.py your_script.py
```
where `python` can be overridden by setting the variable `g:syntastic_python_python_exec` (or its local version).  If you must change the default to either `python2` or `python3`, the simplest way to do it without making a mess is to add `'exec': 'python3'` (or `pyhton2`) to the dict in the `g:SyntasticRegistry.CreateAndRegisterChecker()` call in `python.vim`:
```vim
call g:SyntasticRegistry.CreateAndRegisterChecker({
    \ 'filetype': 'python',
    \ 'exec': 'python3',
    \ 'name': 'python'})
```

[venv]: https://github.com/vim-syntastic/syntastic#faqpython

**Comment by praiskup** [comment]
Thanks.
