### ISSUE TITLE
skip checks for certian linters

### ISSUE THREAD

**Issue by Luticus** [vim-syntastic/syntastic#2252]
I'm trying to set up the ansible linter to skip check number 204 because I don't want the linter telling me the names in my stig playbook are too long.  It creates too much noise and makes the files hard to debug.  Is this supported?  How can I do it?  I've tried adding a .ansible-lint conf file to the directory, setting alises pointing the ansible-lint command to always use a specific conf file, etc.  When I run the ansible linter outside of vim it respects my wishes but for some reason I can't manage to get syntastic to run it that way.  There doesn't seem to be a way to pass arguments to ansible-lint from syntastic like there are for others such as python, or at least I couldn't find any documentation on any.  If anyone has any idea, help would be appreciated.

**Comment by lcd047** [comment]
> Is this supported?

Within reasonable limits.

> How can I do it?

You can tell `ansible-lint` to skip the checks, or you can tell syntastic to kill the (i)relevant messages after the fact.  The first approach is of course preferred.

> I've tried adding a .ansible-lint conf file to the directory,

To what directory?  As far as I can tell, `ansible-lint` only looks for an `.ansible-lint` only in the current directory.  When run from syntastic that's Vim's idea of current directory.

> setting alises pointing the ansible-lint command to always use a specific conf file, etc.

Nope, Vim doesn't care about shell aliases.

> When I run the ansible linter outside of vim it respects my wishes but for some reason I can't manage to get syntastic to run it that way.

You need to find out those reasons.  This might be a good starting pint: `:h syntastic-debug`.

> There doesn't seem to be a way to pass arguments to ansible-lint from syntastic like there are for others such as python,

There is, and it works the same way.  Just use `ansible_ansible_lint` (not `ansible_ansible-lint`) in variable names instead of `python_flake8`, `pyrhon_pylint`, or whatever.

> or at least I couldn't find any documentation on any. If anyone has any idea, help would be appreciated.

It's documented: `:h syntastic-checker-options`.

**Comment by Luticus** [comment]
let g:syntastic_ansible_ansible_lint_args= "-c /Users/joe/.ansible-lint" let me set it up.

I wasn't respecting having a .ansible-lint in the working directory, still not sure why but you clueing me into the variable name help and I managed to make it work by placing a .ansible-lint config file in home.  Also note that ~ does not work, you should pass full path apparently.  This method also has the added benefit of allowing me to set up a global file so my exclusions work in all cases and I don't have to keep .ansible-lint files in all my projects, because ick.

The reason I didn't think that particular args var was documented was because if you look a :h syntastic-checkers and check pythons pylint you'll see a like like this:   let g:syntastic_python_pylint_post_args =
        \ '--msg-template="{path}:{line}:{column}:{C}: [{symbol} {msg_id}] {msg}"'

where no such line exists for ansible.

If I go to :h syntastic-checker-options and do a search for ansible, noting returns.  It may be documented in a generic way, but i couldn't find anything that listed the full variable name.  Not even your post does that, I had to put together that it was:  g:syntastic_ansible_ansible_lint_args.  Perhaps it could be included in the ansible documentation in syntastic-checkers the way pythons is?  If I'd seen that full variable name somewhere I'd have been on the right track.

Anyway, thanks for your help.  I'll continue to mess around with it some more.
