### ISSUE TITLE
syntastic not working on neovim

### ISSUE THREAD

**Issue by eskinderg** [vim-syntastic/syntastic#2259]
I have neovim with the following configs in my vimrc
I have tsc installed globally on my ubuntu machine
if i do tsc -v, i get Version 2.7.1

Plugins related to typescript:
```
  Plug 'leafgarland/typescript-vim', { 'for': 'typescript' } "Typescript syntax highlight
  Plug 'mhartington/nvim-typescript', {'do': './install.sh'} " Autocompletion of Typescript

```

i have this for my syntastic config
```
autocmd BufNewFile,BufReadPost *.ts set filetype=typescript

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:nvim_typescript#diagnosticsEnable  = 0
"let g:syntastic_debug = 3

" Cusrom Syntastic
let g:syntastic_error_symbol = '✗'
" let g:syntastic_error_symbol = '⚡'
let g:syntastic_style_error_symbol = '⚡'
let g:syntastic_warning_symbol = '⚠⚠'
let g:syntastic_style_warning_symbol = '≈≈'
" let g:syntastic_typescript_checkers = ['tslint']
" let g:syntastic_typescript_checkers = ['tsuquyomi', 'tslint']
" let g:syntastic_typescript_checkers = ['tslint', 'tsc']
" let g:syntastic_typescript_checkers = ['tslint', 'tsc', 'nvim-ts']
" let g:syntastic_javascript_checkers = ['eslint']
" let g:syntastic_typescript_checkers = ['nvim-ts']
let g:syntastic_typescript_checkers = ['tslint']
let g:syntastic_javascript_checkers = ['eslint']
" let g:syntastic_aggregate_errors = 1
" let g:syntastic_scss_checkers = ['scss_lint']
" let g:syntastic_always_populate_loc_list = 1
let g:syntastic_enable_signs = 1
let g:syntastic_debug = 3
" leafgarland config
let g:typescript_compiler_binary = 'tsc'
let g:typescript_compiler_options = ''
```
:SyntasticInfo
```
Syntastic version: 3.9.0-38 (Vim 800, Neovim, Linux)
Info for filetype: typescript
Global mode: active
Filetype typescript is active
The current file will be checked automatically
Available checkers: -
Currently enabled checkers: -
syntastic: 526.212402: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shelltemp = 1, &shellxquote = ''
, &autochdir = 0, &shellxescape = ''
```

Any help would be appricated.

**Comment by lcd047** [comment]
Since you mention NeoVim: syntastic is not tested with NeoVim.  It _mostly_ works, but if you're reporting a bug I'll consider looking at it only if the problem can be reproduced with Vim.

Related to your problem: syntastic itself supports three checkers for `typescript`: `lynt`, `tslint`, and `eslint` (cf. `:h syntastic-checkers-typescript`).  In order for these to work you need (working installations of) Lynt, TSLint, and ESLint respectively.  A working `tsc` is not enough.  Thus the result you see above.

Other checkers that you tried, `tsuquyomi`, `nvim-ts`, `tsc` are not provided by syntastic.  You need third party plugins to enable them, and their functioning is mostly unrelated to syntastic (syntastic provides only the framework for working with checkers).  So if you have problems with any of these you need to report to their corresponding authors.
