### ISSUE TITLE
Running puppet as checker from docker container

### ISSUE THREAD

**Issue by picardrulez** [vim-syntastic/syntastic#2270]
I doubt this is supported by you guys but I figured I'd try anyway.  I've set up a docker image locally running puppet and am attempting to get syntastic to use it in lieue of puppet installed locally.

I've made a wrapper script called /usr/local/bin/puppet with the following contents:
`#!/bin/bash
docker run -v $(pwd):/tmp puppet "$1" "$2 "$3"`

which works as intended in my shell:
`>puppet parser validate init.pp`
`Error: Could not parse for environment production: Syntax error at ',' at /tmp/init.pp:1`

Not so much from syntastic though.  Here's my output with debug=3:

syntastic: 340.275816: &shell = '/usr/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredir = '>%s 2>&1', &shellslash = 0, &shelltemp = 1, &shellxquote = '', &shellxescape = ''

syntastic: 340.276084: UpdateErrors (auto): default checkers
syntastic: 340.276445: CacheErrors: default checkers
syntastic: 340.277664: g:syntastic_aggregate_errors = 0
syntastic: 340.277892: getcwd() = '/home/gscott/repos/puppet/puppet-recipes/modules/debbuilder/manifests'
syntastic: 340.278332: CacheErrors: Invoking checker: puppet/puppet
syntastic: 340.279095: SyntasticMake: called with options: {'errorformat': '%-Gerr: Try ''puppet help parser validate'' for usage,%-GError: Try ''puppet help parser validate'' for usage,%A%t%*[a-zA-Z]: %m at %f
:%l:%c,%A%t%*[a-zA-Z]: %m at %f:%l', 'makeprg': 'puppet parser validate --color=false init.pp'}
syntastic: 341.951572: checker output: ['']
syntastic: 341.951967: raw loclist: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}]
syntastic: 341.952236: getLocList: checker puppet/puppet returned 0
syntastic: 341.952417: puppet/puppet raw: [{'lnum': 0, 'bufnr': 0, 'col': 0, 'valid': 0, 'vcol': 0, 'nr': -1, 'module': '', 'type': '', 'pattern': '', 'text': ''}]
syntastic: 341.952614: quiet_messages filter: {}
syntastic: 341.952862: CacheErrors: Checker puppet/puppetlint is not available
syntastic: 341.953029: aggregated: {'_sorted': 0, '_name': '', '_owner': 1, '_columns': 1, '_rawLoclist': []}

Here's my output from SyntasticInfo:
Syntastic version: 3.6.0-96 (Vim 801, Linux)
Info for filetype: puppet
Global mode: active
Filetype puppet is active
The current file will be checked automatically
Available checker: puppet
Currently enabled checker: puppet

And here are my vimrc settings regarding syntastic:
let g:syntastic_debug=3
let g:syntastic_enable_signs=1
let g:syntastic_auto_jump=0
let g:syntastic_auto_loc_list=1
let g:syntastic_jsl_conf="~/.vim/config/jsl.conf"

**Comment by lcd047** [comment]
> I doubt this is supported by you guys

You're right, it isn't, :smile: but not for the reason you might suspect.

The easy part: your wrapper doesn't work because either `$PATH` in Vim is not the same as `$PATH` in a terminal (cf. [FAQ][FAQ]), or because `puppet` inside the script references the wrapper (it can actually be a lot more hairy, but it doesn't really matter).  Whatever the reason, the solution is to use different names and qualify paths:

- Write a script `/usr/local/bin/puppet.sh`:
```sh
#!/usr/bin/env bash
docker run -v "$(pwd)":/tmp /path/to/puppet "$@"
```
- Point syntastic to it:
```vim
let g:syntastic_puppet_puppet_exec = '/usr/local/bin/puppet.sh'
```
The hard part: your wrapper references `/tmp/init.pp` while Vim expects `$(pwd)/init.pp`.

Now an easy way around this would be to install Vim, Puppet, and whatever else inside your container, and run them there -- but that kind of defeats the purpose of running Docker in the first place.

So you're left with changing `/tmp/init.pp` to `$(pwd)/init.pp` in your script, or in Vim before syntastic gets to see it.

Doing it in your script without messing anything else is an interesting exercise.  It's relatively easy in the case of `puppet`, and impossible to handle in a generic way for all linters.

Doing it it Vim looks more or less like this (not tested):
```vim
let g:docker_src = '/home/gscott/repos/puppet/puppet-recipes/modules/debbuilder/manifests/'
let g:docker_dst = '/tmp/'


function! DockerTranslate(key, val)
    let ret = a:val

    if has_key(ret, 'bufnr')
	let fname = fnamemodify(simplify(bufname(a:val.file)), ':p')
	if strpart(fname, 0, strlen(g:docker_dst)) ==# g:docker_dst
	    let fname = g:docker_src . strpart(fname, strlen(g:docker_dst))
            execute 'badd' fnameescape(fname)
            let ret.bufnr = syntastic#util#fname2buf(fname)
	endif
    endif

    return ret
endfunction


function! SyntasticCheckHook(errors)
    if !empty(a:errors)
	call map(a:errors, function('DockerTranslate'))
    endif
endfunction
```
This might work in principle for all checkers, not just `puppet`, but the problem is many of the Vim internals involved are fragile, and I'm stretching the context where they're supposed to be used.

[FAQ]: https://github.com/vim-syntastic/syntastic#faqinfo

**Comment by picardrulez** [comment]
I think the path is good within vim because I can run :echo system(pupper --version)  and it returns fine.  Also the script I have above is already using $(pwd), maybe I'm missing something in that though.  Actually the way your hitting the user arguments looks interesting and I"m going to try that when I get home.  I've been deep in golang so much lately that I've completely forgotten the intricacies of bash (to the point where I almost just wrote this wrapper in golang lol)  It seems like the problem is happening with the way the arguments are getting passed though so hopefully that'll fix it.  I'll update here as soon as I find out.  thanks!

**Comment by picardrulez** [comment]
haha changing the user argument in the script to "$@" was all it took!  Thank you so much my man!
