### ISSUE TITLE
default config breaks restricted vim (rvim)

### ISSUE THREAD

**Issue by praiskup** [vim-syntastic/syntastic#2288]
https://bugzilla.redhat.com/show_bug.cgi?id=1773723

The thing is that it's not trivial to detect restricted environment:
https://stackoverflow.com/questions/16690202/how-to-detect-if-vim-is-running-in-restricted-mode

**Comment by lcd047** [comment]
Right, syntastic can't run in `rvim`.  Check added 39b35b23.

On a side note: syntastic should never be enabled by default in distribution packages.

**Comment by praiskup** [comment]
> syntastic should never be enabled by default in distribution packages

Is there some document telling packagers how to do this properly?  I could
stop installing stuff under `/usr/share/vim/vimfiles/autoload/syntastic`, but it
would be pretty painful to enable syntastic in `~/.vimrc`, right?

**Comment by lcd047** [comment]
First please note that syntastic is essentially dead, [ALE][ALE] should be preferred instead, since it allows asynchronous checking.  If you must use syntastic then please note that there is no configuration that works reasonably in all common situations, and thus syntastic shouldn't be enabled until it's explicitly configured by the user.   This is a development tool, the vast majority of users don't need it anyway, and if run unconfigured it just slows down Vim startup for no reason.

Now, Vim 8 has a package system, please see `:h packages`.  Within this system plugins can be loaded on demand by placing them in a special directory and using `packadd` (cf. `:h pack-add`).  I don't know how this meshes with RH packaging, but I'd say using Vim's package system would still be substantially better than just dropping things in `autoload`.

[ALE]: https://github.com/dense-analysis/ale

**Comment by praiskup** [comment]
> ALE should be preferred instead

Thanks for the info.  I'll try to take a look at that.

> Now, Vim 8 has a package system, please see :h packages

ack
