### ISSUE TITLE
Populate erros list without open the Errors window

### ISSUE THREAD

**Issue by rafaelleru** [vim-syntastic/syntastic#2299]
I recently migrated to vim from emacs and I am trying to set syntastic to work with python.

I want to check the file both on open and writes operations but I don't want the Errors window to be opened when I open a file. What options should I set? 

So my ideal setup will be a vim screen only showing errors in the lateral of the lines, without the inferior window being opened each time I open a file.

I cannot figure out myself. 

Regards.

**Comment by lcd047** [comment]
Automatic opening of the error window is controlled by `auto_loc_list` (cf. `:h 'syntastic_auto_loc_list'`), but there is no split mode that behaves differently when checking a file on open vs. checking it on write.

On a side note: you should consider using [ALE][ALE] instead of syntastic, as it's actually maintained and it uses Vim 8 features to run checks asynchronously.

[ALE]: https://github.com/dense-analysis/ale
