### ISSUE TITLE
bash extended globbing reported as syntax error

### ISSUE THREAD

**Issue by rphair** [vim-syntastic/syntastic#2309]
vim version 8.0.1453 - Syntastic version: 3.10.0-8 (Vim 800, Linux)

I'm an end-user of vim plugins, not a plugin developer.  Today my vim environment reported
> syntax error near unexpected token `('

... when I added a bash [Extended Glob](https://mywiki.wooledge.org/BashGuide/Patterns#Extended_Globs) expression to my `~/.bash_aliases` file.  I can reproduce what I'm seeing with this file and then editing it in Vim with Syntastic:
```
#!/usr/bin/env bash
shopt -s extglob
# Echo all filenames containing either "foo" or "bar".
echo *@(foo|bar)*
```

If you comment out the `shopt` line, the bash script will fail with the syntax error that the linter is reporting.  My OS comes with `extglob` enabled by default in the interactive environment but not in scripts, which is perhaps why the bash linter doesn't accept it.  I have no idea where these subtleties would be documented, let alone knowing how to work around them.

I also don't know if the `sh` linter is the correct one for bash.  In my testing environment above, `set filetype` shows `sh` and `set shell` is `/bin/bash`, both set automatically.  I've tried setting this in `.vimrc` and it doesn't have any affect on the problem:
```
let g:syntastic_shell = "/bin/bash"
```

On the sample file above, `:SyntasticInfo` reports:
> Info for filetype: sh
> Global mode: active
> Filetype sh is active
> The current file will be checked automatically
> Available checker: sh
> Currently enabled checker: sh

I can get the output of `:mes` on request but I have a feeling this is something more basic.  I use other syntax unique to Bash that's not valid in Bourne Shell, and I've never had a problem with it before.  That's why I think the problem is with "extended globbing" rather than the choice of linter.

This is the limit of what I know how to investigate without someone's help.  Here is a complete list of the programs my Vim IDE is using, in order.  I've updated all these plugins as of today but haven't tried disabling or removing any of them:
```
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-syntastic/syntastic'
Plugin 'preservim/nerdtree'
Plugin 'preservim/nerdcommenter'
Plugin 'majutsushi/tagbar'
Plugin 'evidens/vim-twig'
Plugin 'asm89/twig-lint'
Plugin 'groenewege/vim-less'
Plugin 'vim-vdebug/vdebug'
Plugin 'https://git.drupal.org/project/vimrc.git', {'rtp': 'bundle/vim-plugin-for-drupal/'}
```

**Comment by lcd047** [comment]
First, you're barking up the wrong tree: syntastic it a Vim script, it doesn't know (nor cares) about the contents of your files.  What syntastic does is run third-party linters against your files, parses the linters' output, and shows you the results in a window.  That's all syntastic does.  So if you disagree with the error messages shown by syntastic the problem is with one of the linters, not syntastic itself.

Next, assuming it's actually syntastic and not some other plugin that shows the error (you'd be surprised :smile:), and assuming it's actually the `sh` checker that gets run, you should be able to reproduce the problem in the terminal, outside of Vim and out of the reach of syntastic.  To do that you'd run syntastic in debug mode (`:h syntastic-debug`) to find out what command the `sh` checker runs.  In this case that would be `bash -n your_script.sh`.

And indeed running that in a terminal produces the error you're seeing:
```sh
$ bash -n your_script.sh 
your_script.sh: line 4: syntax error near unexpected token `('
your_script.sh: line 4: `echo *@(foo|bar)*'
```
To fix this you need to change the command so that it won't produce the error.  Namely, you need to tell `bash` extended patterns are cool.  This seems to work (i.e. it doesn't produce any output):
```sh
$ bash -O extglob -n your_script.sh
```
So to take that back to syntastic you need to add `-O extglob` as an option to the `sh` checker:
```vim
let g:syntastic_sh_sh_args = "-O extglob"
```
Which seems to do the job.

**Comment by rphair** [comment]
thank you for your reasoning & knowledge.  I did know that Syntastic was only the starting point, but didn't even know how to find the correct linter let alone modify its behaviour.  Hence my dumping this into this issue queue and my gratitude for your extraordinary help... I'll try to use your reasoning to fix any similar problems in the future.
