### ISSUE TITLE
Update documentation to provide instructions using vim packages

### ISSUE THREAD

**Issue by everybodyeverybody** [vim-syntastic/syntastic#2318]
Hi,

I should have raised this as an issue rather than issue a pull request immediately.

For documentation, this comment was left on my change to README.markdown:

> Second, it adds an example of installing syntastic "directly into vim version 8+ from git". This is too restrictive to be useful, redundant since the main README already mentions :help packages, and struggles to get the Markdown syntax right.

Is having direct instructions on how to use vim packages to install this seen as redundant? 

I believe providing people instructions on an easy, vim supported way to install this is useful and time saving. Nor is this more restrictive than using a separate plugin manager.

**Comment by lcd047** [comment]
> Is having direct instructions on how to use vim packages to install this seen as redundant?

Yes.  Syntastic is a development plugin, you need at least _some_ familiarity with Vim scripting in order to use it effectively, at which point you probably know several perfectly good methods of installing plugins.  In particular in the 10+ years history of syntastic there has never been any question about installing it, whatever you do for other plugins also works for syntastic.

Also, syntastic is essentially dead.  The only reason to use it these days instead of an asynch checker such as [ALE][ALE] is because you're stuck with Vim 7 for whatever reasons.  "Improving" docs about installation at this point basically wastes everybody's time, and consequently is pretty low priority.  Sorry about that.

[ALE]: https://github.com/dense-analysis/ale
