### ISSUE TITLE
How can I specify a checker's path?

### ISSUE THREAD

**Issue by nerdo** [vim-syntastic/syntastic#2363]
I apologize in advance if the answer to this is somewhere obvious, but I did some searching in the last day or so and haven't been able to find any clear answer.

I have a situation where I want to use the `php` binary in a docker container for a specific project. but my vim setup exists in my host - I'd like to avoid having to set it up inside the container for various reasons, one of which is that the container is using an old version of Ubuntu (to match production) and it would complicate things to get vim working as well inside the container as it is on my host.

That said, I can't seem to find a way to set the path to the command used for each checker. I found some thing somewhere referencing ruby which described something like setting `syntastic_ruby_exec` but trying to set `syntastic_php_exec` didn't seem to do anything.

Is what I want to do possible? Are there any alternatives that don't involve obvious, but less than ideal solutions like setting up a php symlink or alias on my host system to use the container's?

**Comment by lcd047** [comment]
The path to `php` can be specified with `syntastic_php_php_exec` (and similarly for `ruby`; "short form" variables such as `syntastic_ruby_exec` exist only for legacy reasons).

However changing that still won't do you any good, since checkers running inside a container return filenames relative to the container's root, while Vim and syntastic need to see the paths from the real root.  This has been discussed in the past (cf. f.i. #2270), and it doesn't really have any easy solution.  Some people have suggested workarounds for [ALE][ALE] though (cf. #2346).  And you should be using [ALE][ALE] instead syntastic these days anyway.

[ALE]: https://github.com/dense-analysis/ale

**Comment by nerdo** [comment]
Thanks for pointing me at ALE! I was not aware of it. I'll use that moving forward.
